name: Pipelineworkflow

on:
  push:
    branches:
      -  main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipeline Action
          uses: Azure/pipeline@v1
          with:
            azure-devops-project-url: https://dev.azure.com/v-2amitc/mytestproj
            aure-pipeline-name: 'gitaction'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN}}

        